In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

X, y = make_blobs(n_samples=30, centers=3, n_features=3, random_state=42)



In [2]:

k_means = KMeans(n_clusters=3)
y_hat = k_means.fit_predict(X)


In [3]:
print(y_hat)

[2 2 2 1 0 1 0 0 2 0 1 0 2 2 1 1 1 2 2 0 0 1 2 0 2 0 1 0 1 1]


In [4]:
print(y)

[2 2 2 0 1 0 1 1 2 1 0 1 2 2 0 0 0 2 2 1 1 0 2 1 2 1 0 1 0 0]


In [6]:
np.mean(X)

-0.031439890354080784

In [7]:
len(X[0,:])

3

In [8]:
len(X)

30

In [9]:
import chart_studio.plotly as py
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import cufflinks as cf
import plotly.graph_objs as go


In [25]:
data = [1,2,3,2,1,9,8,11,12,10,14,25,26,24,30,22,24,27]

trace1 = go.Scatter(x=data, y=[0 for num in data],mode='markers', name='Data',
                    marker=dict(size=12)
                    )

layout = go.Layout(title='1D vector')

traces = [trace1]

fig = go.Figure(data=traces, layout=layout)
plot(fig)


'temp-plot.html'

In [26]:
n_clusters = 3
c_centers = np.random.choice(data, n_clusters)
print(c_centers)


[ 2  1 25]


In [27]:
np.random.choice(data)

24

In [28]:
deltas = np.array([np.abs(point - c_centers) for point in X])

In [29]:
print(deltas)

[[10.66277446  6.01423437 22.30457426]
 [11.62758609  7.0672342  23.18986119]
 [12.25707822  7.36601453 22.07416727]
 [ 4.1149646   8.13650529 20.87555683]
 [ 0.7468701   8.41776885 33.22678769]
 [ 5.25160446  7.31094233 22.49974182]
 [ 2.75148273  6.68598747 31.66147128]
 [ 0.72816748  8.08679308 32.50358699]
 [10.58121089  6.63803581 21.60583763]
 [ 0.43721362  6.69991085 32.77831753]
 [ 5.14475736  6.99273393 20.52187655]
 [ 0.90742158  9.0101795  31.74568071]
 [11.13028043  3.66834687 22.63218182]
 [11.09495794  5.95569719 21.70396614]
 [ 3.69275254  6.49041013 20.78816723]
 [ 5.43328046  5.40173712 19.40975148]
 [ 5.10945147  8.96172595 20.06908716]
 [11.26519655  6.82497125 21.81951311]
 [ 9.3428935   6.66170417 19.60540351]
 [ 1.53498361  6.77998022 32.05784171]
 [ 0.10263406  6.90666366 31.08451413]
 [ 5.04284643  8.00875827 20.58957162]
 [11.75871856  5.92488453 23.03856385]
 [ 0.55529248  6.99187873 30.98577726]
 [10.81932743  5.78910646 24.47275364]
 [ 0.85493072  8.88871253