In [1]:
import numpy as np

In [2]:
x = np.array([[1,0,4],[3,3,1]])
y = np.array([[2,5],[1,1],[3,2]])
x.dot(y)

array([[14, 13],
       [12, 20]])

In [3]:
x

array([[1, 0, 4],
       [3, 3, 1]])

In [4]:
x.ndim

2

In [5]:
x.size

6

In [6]:
x.dtype

dtype('int64')

In [7]:
x = np.array([[1,2,3],[4,5,6]], dtype=np.float)

In [8]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [9]:
x.dtype

dtype('float64')

In [10]:
x_copy = np.array(x, dtype=int)

In [11]:
x_copy.dtype

dtype('int64')

In [12]:
x_copy_float = np.array(x, dtype=float)

In [13]:
x_copy_float.dtype

dtype('float64')

In [14]:
my_list = [2,4,6,8]
my_array = np.asarray(my_list)
type(my_array)

numpy.ndarray

In [15]:
my_array +2

array([ 4,  6,  8, 10])

In [16]:
my_list +2

TypeError: can only concatenate list (not "int") to list

In [18]:
my_array *2

array([ 4,  8, 12, 16])

In [19]:
second_array = np.zeros(4)

In [20]:
second_array +4

array([4., 4., 4., 4.])

In [22]:
third_array = np.zeros(4) +3

In [23]:
third_array

array([3., 3., 3., 3.])

In [24]:
my_array - third_array

array([-1.,  1.,  3.,  5.])

In [25]:
third_array / my_array

array([1.5  , 0.75 , 0.5  , 0.375])

In [26]:
second_array = np.ones(4) + 3

In [28]:
second_array = np.identity(4)

In [29]:
second_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
third_array = np.identity(4) + 3

In [31]:
third_array

array([[4., 3., 3., 3.],
       [3., 4., 3., 3.],
       [3., 3., 4., 3.],
       [3., 3., 3., 4.]])

In [32]:
my_array - third_array

array([[-2.,  1.,  3.,  5.],
       [-1.,  0.,  3.,  5.],
       [-1.,  1.,  2.,  5.],
       [-1.,  1.,  3.,  4.]])

In [33]:
my_array

array([2, 4, 6, 8])

In [34]:
second_array / my_array

array([[0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.25      , 0.        , 0.        ],
       [0.        , 0.        , 0.16666667, 0.        ],
       [0.        , 0.        , 0.        , 0.125     ]])