In [1]:
import numpy as np

In [3]:
x = np.array([[1,0,4],[3,3,1]])
y = np.array([[2,5],[1,1],[3,2]])
x.dot(y)

array([[14, 13],
       [12, 20]])

In [4]:
x

array([[1, 0, 4],
       [3, 3, 1]])

In [5]:
x.ndim

2

In [6]:
x.size

6

In [7]:
x.dtype

dtype('int64')

In [8]:
x = np.array([[1,2,3],[4,5,6]], dtype=np.float)

In [9]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
x.dtype

dtype('float64')

In [12]:
x_copy = np.array(x, dtype=int)

In [13]:
x_copy.dtype

dtype('int64')

In [14]:
x_copy_float = np.array(x, dtype=float)

In [15]:
x_copy_float.dtype

dtype('float64')

In [17]:
my_list = [2,4,6,8]
my_array = np.asarray(my_list)
type(my_array)

numpy.ndarray

In [18]:
my_array +2

array([ 4,  6,  8, 10])

In [19]:
my_list +2

TypeError: can only concatenate list (not "int") to list