In [1]:
from sklearn.datasets import load_boston
dataset = load_boston()

In [2]:
samples.shape

NameError: name 'samples' is not defined

In [3]:
samples, label, feature_namaes = dataset.data, dataset.target, dataset.feature_names

In [4]:
samples = dataset.data
label = dataset.target
feature_names = dataset.feature_names

In [5]:
samples.shape

(506, 13)

In [6]:
label.shape

(506,)

In [7]:
print(dataset.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [8]:
import numpy as np

In [9]:
np.isnan(samples)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [10]:
sum(np.isnan(samples))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
samples.shape

(506, 13)

In [12]:
np.isnan(np.sum(samples))

False

In [13]:
minimum = np.round(np.amin(samples, axis=0), decimals=1)

In [14]:
minimum

array([  0. ,   0. ,   0.5,   0. ,   0.4,   3.6,   2.9,   1.1,   1. ,
       187. ,  12.6,   0.3,   1.7])

In [15]:
range_column = np.round(np.ptp(samples, axis=0), decimals=1)

In [16]:
maximum = np.round(np.amax(samples, axis=0), decimals=1)

In [17]:
mean = np.round(np.mean(samples, axis=0), decimals=1)

In [18]:
median = np.round(np.median(samples, axis=0), decimals=1)
variance = np.round(np.var(samples, axis=0), decimals=1)

In [19]:
tenth_percentile = np.round(np.percentile(samples, 10, axis=0), decimals =1)
ninty_percentile = np.round(np.percentile(samples, 90, axis=0), decimals=1)

In [24]:
Basic_Stastics = np.vstack((minimum, maximum, range_column, mean, median, variance, tenth_percentile, ninty_percentile))

In [25]:
Basic_Stastics

array([[0.00000e+00, 0.00000e+00, 5.00000e-01, 0.00000e+00, 4.00000e-01,
        3.60000e+00, 2.90000e+00, 1.10000e+00, 1.00000e+00, 1.87000e+02,
        1.26000e+01, 3.00000e-01, 1.70000e+00],
       [8.90000e+01, 1.00000e+02, 2.77000e+01, 1.00000e+00, 9.00000e-01,
        8.80000e+00, 1.00000e+02, 1.21000e+01, 2.40000e+01, 7.11000e+02,
        2.20000e+01, 3.96900e+02, 3.80000e+01],
       [8.90000e+01, 1.00000e+02, 2.73000e+01, 1.00000e+00, 5.00000e-01,
        5.20000e+00, 9.71000e+01, 1.10000e+01, 2.30000e+01, 5.24000e+02,
        9.40000e+00, 3.96600e+02, 3.62000e+01],
       [3.60000e+00, 1.14000e+01, 1.11000e+01, 1.00000e-01, 6.00000e-01,
        6.30000e+00, 6.86000e+01, 3.80000e+00, 9.50000e+00, 4.08200e+02,
        1.85000e+01, 3.56700e+02, 1.27000e+01],
       [3.00000e-01, 0.00000e+00, 9.70000e+00, 0.00000e+00, 5.00000e-01,
        6.20000e+00, 7.75000e+01, 3.20000e+00, 5.00000e+00, 3.30000e+02,
        1.90000e+01, 3.91400e+02, 1.14000e+01],
       [7.38000e+01, 5.42900e+