In [3]:
from sklearn.datasets import load_boston
dataset = load_boston()

AttributeError: feature_namaes

In [5]:
samples.shape

NameError: name 'samples' is not defined

In [8]:
samples, label, feature_namaes = dataset.data, dataset.target, dataset.feature_names

In [7]:
samples = dataset.data
label = dataset.target
feature_names = dataset.feature_names

In [9]:
samples.shape

(506, 13)

In [10]:
label.shape

(506,)

In [12]:
print(dataset.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [14]:
import numpy as np

In [15]:
np.isnan(samples)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [16]:
sum(np.isnan(samples))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
samples.shape

(506, 13)

In [18]:
np.isnan(np.sum(samples))

False

In [21]:
minimum = np.round(np.amin(samples, axis=0), decimals=1)

In [22]:
minimum

array([  0. ,   0. ,   0.5,   0. ,   0.4,   3.6,   2.9,   1.1,   1. ,
       187. ,  12.6,   0.3,   1.7])