In [1]:
import numpy as np

In [2]:
c = np.ones((4,4))

In [3]:
c * c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
c.dot(c)

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [7]:
y = np.arange(15).reshape(3,5)
x = np.arange(10).reshape(2,5)

In [10]:
new_array = np.vstack((y,x))
new_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [13]:
y = np.arange(15).reshape(5,3)
x = np.arange(10).reshape(5,2)
new_array = np.hstack((y, x))

In [14]:
new_array

array([[ 0,  1,  2,  0,  1],
       [ 3,  4,  5,  2,  3],
       [ 6,  7,  8,  4,  5],
       [ 9, 10, 11,  6,  7],
       [12, 13, 14,  8,  9]])

In [15]:
from scipy import stats
x = np.random.rand(100,10)

In [25]:
n, min_max, mean, var, skew, kurt = stats.describe(x)

In [26]:
mean

array([0.5061051 , 0.51673771, 0.46550227, 0.57604619, 0.45398573,
       0.52058901, 0.4801686 , 0.49524424, 0.52008153, 0.52259584])

In [31]:
np.mean(x[1, :])

0.392935541257562

In [33]:
np.mean(x[:, 1])

0.5167377088736176

In [34]:
stats.describe(x)

DescribeResult(nobs=100, minmax=(array([0.01858474, 0.01793637, 0.01073441, 0.02110187, 0.00597287,
       0.00063126, 0.00557672, 0.01131781, 0.00646262, 0.01003841]), array([0.9895862 , 0.99673171, 0.97477267, 0.99663194, 0.99897187,
       0.99791667, 0.97371695, 0.9909289 , 0.98357031, 0.99924822])), mean=array([0.5061051 , 0.51673771, 0.46550227, 0.57604619, 0.45398573,
       0.52058901, 0.4801686 , 0.49524424, 0.52008153, 0.52259584]), variance=array([0.07811785, 0.07067945, 0.07782962, 0.08304925, 0.07301661,
       0.07739577, 0.07963006, 0.0915403 , 0.08371684, 0.09959484]), skewness=array([ 0.2193646 , -0.03878612,  0.14375097, -0.11228343,  0.11878262,
       -0.14422177,  0.03215641,  0.04269751, -0.15088168, -0.06907972]), kurtosis=array([-1.06926229, -1.00277992, -1.21328235, -1.28752884, -1.05903462,
       -1.07346596, -1.23105985, -1.32878065, -1.22844642, -1.35069921]))

In [35]:
min_max

(array([0.01858474, 0.01793637, 0.01073441, 0.02110187, 0.00597287,
        0.00063126, 0.00557672, 0.01131781, 0.00646262, 0.01003841]),
 array([0.9895862 , 0.99673171, 0.97477267, 0.99663194, 0.99897187,
        0.99791667, 0.97371695, 0.9909289 , 0.98357031, 0.99924822]))

In [36]:
np.min(x[:,0])

0.018584736854548645

In [37]:

np.min(x[:,1])

0.01793636951239419