In [1]:
import numpy as np

In [2]:
c = np.ones((4,4))

In [3]:
c * c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
c.dot(c)

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [6]:
y = np.arange(15).reshape(3,5)
x = np.arange(10).reshape(2,5)

In [7]:
new_array = np.vstack((y,x))
new_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [8]:
y = np.arange(15).reshape(5,3)
x = np.arange(10).reshape(5,2)
new_array = np.hstack((y, x))

In [9]:
new_array

array([[ 0,  1,  2,  0,  1],
       [ 3,  4,  5,  2,  3],
       [ 6,  7,  8,  4,  5],
       [ 9, 10, 11,  6,  7],
       [12, 13, 14,  8,  9]])

In [10]:
from scipy import stats
x = np.random.rand(100,10)

In [11]:
n, min_max, mean, var, skew, kurt = stats.describe(x)

In [12]:
mean

array([0.45802189, 0.5144025 , 0.49692236, 0.5008009 , 0.48560434,
       0.51138702, 0.53592295, 0.43079447, 0.53075904, 0.53840558])

In [13]:
np.mean(x[1, :])

0.3681356813215816

In [14]:
np.mean(x[:, 1])

0.5144025007923259

In [15]:
stats.describe(x)

DescribeResult(nobs=100, minmax=(array([0.0230589 , 0.00301361, 0.02007898, 0.01846062, 0.01159604,
       0.00257522, 0.00135995, 0.00085843, 0.01025891, 0.00336086]), array([0.97146935, 0.999964  , 0.98746619, 0.98800272, 0.99683396,
       0.99274037, 0.99767684, 0.99512821, 0.99429478, 0.99944183])), mean=array([0.45802189, 0.5144025 , 0.49692236, 0.5008009 , 0.48560434,
       0.51138702, 0.53592295, 0.43079447, 0.53075904, 0.53840558]), variance=array([0.07813077, 0.08519826, 0.08074852, 0.09209717, 0.07500826,
       0.07652608, 0.0763828 , 0.09196377, 0.085872  , 0.0980303 ]), skewness=array([ 0.18242722, -0.06435511, -0.00570282,  0.07582795,  0.09611914,
       -0.01214205, -0.20187128,  0.24394619, -0.14814292, -0.21531678]), kurtosis=array([-1.04679485, -1.14586956, -1.15946066, -1.34506371, -0.89668418,
       -1.06549491, -0.91623054, -1.24437934, -1.18304275, -1.32377228]))

In [16]:
min_max

(array([0.0230589 , 0.00301361, 0.02007898, 0.01846062, 0.01159604,
        0.00257522, 0.00135995, 0.00085843, 0.01025891, 0.00336086]),
 array([0.97146935, 0.999964  , 0.98746619, 0.98800272, 0.99683396,
        0.99274037, 0.99767684, 0.99512821, 0.99429478, 0.99944183]))

In [17]:
np.min(x[:,0])

0.02305890204933214

In [18]:
np.min(x[:,1])

0.0030136087047559768

In [19]:
len(x)

100

In [20]:
a = np.arange(6).reshape(3,2)
b = np.arange(10).reshape(2,5)

In [21]:
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
np.dot(a,b)

array([[ 5,  6,  7,  8,  9],
       [15, 20, 25, 30, 35],
       [25, 34, 43, 52, 61]])

In [23]:
np.matmul(a,b)

array([[ 5,  6,  7,  8,  9],
       [15, 20, 25, 30, 35],
       [25, 34, 43, 52, 61]])

In [24]:
a@b

array([[ 5,  6,  7,  8,  9],
       [15, 20, 25, 30, 35],
       [25, 34, 43, 52, 61]])

In [25]:
from numpy.linalg import multi_dot
a = np.arange(12).reshape(4,3)
b = np.arange(15).reshape(3,5)
c = np.arange(25).reshape(5,5)

In [26]:
multi_dot([a,b,c])

array([[ 1700,  1855,  2010,  2165,  2320],
       [ 5300,  5770,  6240,  6710,  7180],
       [ 8900,  9685, 10470, 11255, 12040],
       [12500, 13600, 14700, 15800, 16900]])

In [27]:
a = np.arange(9).reshape(3,3)
b = np.arange(3)
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


In [28]:
np.inner(a,b)

array([ 5, 14, 23])

In [29]:
np.outer(a,b)

array([[ 0,  0,  0],
       [ 0,  1,  2],
       [ 0,  2,  4],
       [ 0,  3,  6],
       [ 0,  4,  8],
       [ 0,  5, 10],
       [ 0,  6, 12],
       [ 0,  7, 14],
       [ 0,  8, 16]])

In [30]:
a = np.arange(9)
np.ndim(a)

1

In [31]:
np.outer(a,b)

array([[ 0,  0,  0],
       [ 0,  1,  2],
       [ 0,  2,  4],
       [ 0,  3,  6],
       [ 0,  4,  8],
       [ 0,  5, 10],
       [ 0,  6, 12],
       [ 0,  7, 14],
       [ 0,  8, 16]])

In [32]:
a = np.arange(12).reshape(2,3,2)
b = np.arange(48).reshape(3,2,8)
c = np.tensordot(a,b, axes=([1,0],[0,1]))
print(a)
print(b)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 0  1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14 15]]

 [[16 17 18 19 20 21 22 23]
  [24 25 26 27 28 29 30 31]]

 [[32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47]]]


In [33]:
c

array([[ 800,  830,  860,  890,  920,  950,  980, 1010],
       [ 920,  956,  992, 1028, 1064, 1100, 1136, 1172]])

In [34]:
from sklearn import decomposition, datasets
from sklearn.preprocessing import StandardScaler
data = datasets.load_breast_cancer()

In [35]:
cancer = data.data
cancer = StandardScaler().fit_transform(cancer)

In [36]:
cancer.shape

(569, 30)

In [37]:
before_transformation = data.data
before_transformation[:10,:1]

array([[17.99],
       [20.57],
       [19.69],
       [11.42],
       [20.29],
       [12.45],
       [18.25],
       [13.71],
       [13.  ],
       [12.46]])

In [38]:
cancer[:10, :1]

array([[ 1.09706398],
       [ 1.82982061],
       [ 1.57988811],
       [-0.76890929],
       [ 1.75029663],
       [-0.47637467],
       [ 1.17090767],
       [-0.11851678],
       [-0.32016686],
       [-0.47353452]])

In [42]:
covariance_matrix = np.cov(cancer, rowvar=False)
covariance_matrix.shape

(30, 30)

In [43]:
eig_val_cov, eig_vec_cov = np.linalg.eig(covariance_matrix)
eig_pairs = [(np.abs(eig_val_cov[i]),eig_vec_cov[:,i]) for i in range(len(eig_val_cov))]

In [44]:
eig_pairs

[(13.304990794374563,
  array([0.21890244, 0.10372458, 0.22753729, 0.22099499, 0.14258969,
         0.23928535, 0.25840048, 0.26085376, 0.13816696, 0.06436335,
         0.20597878, 0.01742803, 0.21132592, 0.20286964, 0.01453145,
         0.17039345, 0.15358979, 0.1834174 , 0.04249842, 0.10256832,
         0.22799663, 0.10446933, 0.23663968, 0.22487053, 0.12795256,
         0.21009588, 0.22876753, 0.25088597, 0.12290456, 0.13178394])),
 (5.701374603726144,
  array([-0.23385713, -0.05970609, -0.21518136, -0.23107671,  0.18611302,
          0.15189161,  0.06016536, -0.0347675 ,  0.19034877,  0.36657547,
         -0.10555215,  0.08997968, -0.08945723, -0.15229263,  0.20443045,
          0.2327159 ,  0.19720728,  0.13032156,  0.183848  ,  0.28009203,
         -0.21986638, -0.0454673 , -0.19987843, -0.21935186,  0.17230435,
          0.14359317,  0.09796411, -0.00825724,  0.14188335,  0.27533947])),
 (2.8229101550062303,
  array([-0.00853124,  0.0645499 , -0.00931422,  0.02869953, -0.1042919

In [46]:
sorted_pairs = eig_pairs.sort(key= lambda x: x[0], reverse=True)

In [48]:
for i in eig_pairs:
    print(i[0])

13.304990794374563
5.701374603726144
2.8229101550062303
1.9841275177301978
1.6516332423301194
1.2094822398029734
0.6764088817009056
0.47745625468950725
0.4176287821078174
0.35131087488173407
0.2944331534911643
0.261621161366121
0.24178242132831412
0.15728614921759332
0.0943006956010556
0.08000340447737729
0.059503613530432396
0.05271142221014806
0.049564700212981545
0.031214260553066586
0.030025663090428402
0.027487711338904378
0.024383691354590994
0.018086793984305433
0.015508527134418687
0.008192037117607095
0.006912612579184526
0.0015921360011973828
0.0007501214127189963
0.00013327905666413948


In [49]:
matrix_w = np.hstack((eig_pairs[0][1].reshape(30,1),eig_pairs[1][1].reshape(30,1)))
matrix_w.shape

(30, 2)

In [50]:
eig_pairs[0][1]

array([0.21890244, 0.10372458, 0.22753729, 0.22099499, 0.14258969,
       0.23928535, 0.25840048, 0.26085376, 0.13816696, 0.06436335,
       0.20597878, 0.01742803, 0.21132592, 0.20286964, 0.01453145,
       0.17039345, 0.15358979, 0.1834174 , 0.04249842, 0.10256832,
       0.22799663, 0.10446933, 0.23663968, 0.22487053, 0.12795256,
       0.21009588, 0.22876753, 0.25088597, 0.12290456, 0.13178394])

In [52]:
eig_pairs[1][1]

array([-0.23385713, -0.05970609, -0.21518136, -0.23107671,  0.18611302,
        0.15189161,  0.06016536, -0.0347675 ,  0.19034877,  0.36657547,
       -0.10555215,  0.08997968, -0.08945723, -0.15229263,  0.20443045,
        0.2327159 ,  0.19720728,  0.13032156,  0.183848  ,  0.28009203,
       -0.21986638, -0.0454673 , -0.19987843, -0.21935186,  0.17230435,
        0.14359317,  0.09796411, -0.00825724,  0.14188335,  0.27533947])

In [53]:
transformed = matrix_w.T.dot(cancer.T)

In [54]:
transformed.shape

(2, 569)

In [55]:
transformed = transformed.T

In [56]:
transformed.shape

(569, 2)

In [57]:
from sklearn import decomposition
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
pca = decomposition.PCA(n_components=2)
x_std = StandardScaler().fit_transform(cancer)
pca.fit_transform(x_std)[0]

array([9.19283683, 1.94858307])

In [58]:
x = np.array([2,5,9,0])
np.linalg.norm(x,ord=0)

3.0

# 線型方程式

In [61]:
A = np.array([[2,1,2],[3,2,1],[0,1,1]])
A

array([[2, 1, 2],
       [3, 2, 1],
       [0, 1, 1]])

In [62]:
B = np.array([8,3,4])

In [63]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.2,  0.2, -0.6],
       [-0.6,  0.4,  0.8],
       [ 0.6, -0.4,  0.2]])

In [65]:
np.dot(A_inv,B)

array([-0.2, -0.4,  4.4])

In [67]:
x = np.linalg.solve(A,B)
x

array([-0.2, -0.4,  4.4])

In [68]:
np.allclose(np.dot(A,x),B)

True

In [69]:
from numpy import arange, array, ones, linalg
from pylab import plot, show
x = np.arange(1,11)
A = np.vstack([x, np.ones(len(x))]).T
A

array([[ 1.,  1.],
       [ 2.,  1.],
       [ 3.,  1.],
       [ 4.,  1.],
       [ 5.,  1.],
       [ 6.,  1.],
       [ 7.,  1.],
       [ 8.,  1.],
       [ 9.,  1.],
       [10.,  1.]])

In [70]:
y = [5,6,6.5,7,8, 9.5,10, 10,4, 13.1,15.5]
w = linalg.lstsq(A,y)[0]

LinAlgError: Incompatible dimensions